### ISSUE TITLE
(Not possible (99.99%)) Fix for FL 20.99/21

### ISSUE THREAD

**Issue by azphina** [RafPlayz69YT/FLPTrialStateModder#2]
I recently downloaded the FL Studio 21 Public Beta (also known as 20.99) and it seems the file format has been changed dramatically. FL 20 can read converted 21 files, but cannot recover any data and returns an invalid data error after skipping the version mismatch warning. 21 itself crashes upon loading the converted file. Here's the beta link if you'd like to test it: https://forum.image-line.com/viewtopic.php?t=288863

**Comment by raf13lol** [comment]
didnt know that they changed the file format between beta 4 (which i have) and beta 7

**Comment by raf13lol** [comment]
ill test with beta 8 (extra future proofing) and have a look around in the file

**Comment by raf13lol** [comment]
oh dear, it does crash

**Comment by azphina** [comment]
no more future proofing, FL 21 is released!!!!! uh oh

**Comment by raf13lol** [comment]
does it work

**Comment by raf13lol** [comment]
updated title :grin:

**Comment by azphina** [comment]
![image](https://user-images.githubusercontent.com/98504026/218616324-75dd8135-c880-4fe7-80a5-e067b5b2f4cc.png)
looks like they know now. it DOES say currently nothing's changed though...? [Edit: never mind, new form of copy protection is in place apparently]

**Comment by RafPlayz69YT** [comment]
😱 😱 
top 10 scary things 😔 
1. me getitng in trouble with fl studio 💥 
2. carrot company coming to my house (11 broom grove come here 1v1 shrub me vs fl studio)
3. them trying to shut me down (very rude)
4. me getting banned from fl studio (i will sex their mom if they do)
5. fl studio winning the 1v1 (my bones will be hurt)
6. them bombing my house (my pets will die 😭)
7. scott reveals himself to be scott cawthon and gets fnaf fans on me (ill be screwed because they'll know my address)
8. them doxxing me (😭 so rude only i do that)
9. them telling google to shut me down (i will lose so much stuff if it includes my yt)
10. they will find a way to teleport me to london (very scary i know)

**Comment by azabiphetamine** [comment]
> :scream: :scream:
> top 10 scary things :pensive:
> 
> 1. me getitng in trouble with fl studio :boom:
> 2. carrot company coming to my house (## ##### ##### come here 1v1 shrub me vs fl studio)
> 3. them trying to shut me down (very rude)
> 4. me getting banned from fl studio (i will sex their mom if they do)
> 5. fl studio winning the 1v1 (my bones will be hurt)
> 6. them bombing my house (my pets will die :sob:)
> 7. scott reveals himself to be scott cawthon and gets fnaf fans on me (ill be screwed because they'll know my address)
> 8. them doxxing me (:sob: so rude only i do that)
> 9. them telling google to shut me down (i will lose so much stuff if it includes my yt)
> 10. they will find a way to teleport me to london (very scary i know)

\- graph mark (raf)
